services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexa_talk
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
